services:
  - type: web
    name: ContractVault-SC-2
    env: python
    buildCommand: |
      apt-get update && apt-get install -y wkhtmltopdf
      pip install -r requirements.txt
    startCommand: gunicorn app:app
